[package]
name = "qotw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
pulldown-cmark = "0.10"
pulldown-cmark-to-cmark = "13"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
walkdir = "2"
